# Generated by Django 4.1.7 on 2023-03-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_alter_categorie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitnc',
            name='id',
        ),
        migrations.AddField(
            model_name='produitnc',
            name='produit_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='magasin.produit'),
            preserve_default=False,
        ),
    ]
