# Generated by Django 4.1.7 on 2023-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_remove_produitnc_id_produitnc_produit_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(to='magasin.produit'),
        ),
    ]
